[build]
target-dir = "Target"

[cargo-new]
vcs = "git"

[profile.release]
opt-level = 3
codegen-units = 1
debug = false
lto = true
panic = "abort"
strip = true

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]
